export const ButtonVariantType = {
  ACTION_PRIMARY: 'ACTION_PRIMARY',
  ACTION_SECONDARY: 'ACTION_SECONDARY',
  ACTION_SECONDARY_ALT: 'ACTION_SECONDARY_ALT',
  PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY',
  SECONDARY_ALT: 'SECONDARY_ALT',
} as const;

export const ButtonSizeType = {
  LARGE: 'LARGE',
  SMALL: 'SMALL',
} as const;
