export enum FooterVariants {
  DEFAULT = 'DEFAULT',
  DEFAULT_ALTERNATIVE = 'DEFAULT_ALTERNATIVE',
  REVERSE = 'REVERSE',
  ALTERNATIVE = 'ALTERNATIVE',
  SECONDARY = 'SECONDARY',
  MODAL = 'MODAL',
}
