import path from 'path';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  test: {
    clearMocks: true,
    coverage: {
      exclude: [
        'node_modules/',
        'dist/',
        'build/',
        'coverage/',
        'bundle/',
        'reports/',
        '__reports__/',
        '.storybook/',
        'src/**/types/**',
        'src/**/stories/**',
        'src/**/__stories__/**',
        'src/**/storybook/**',
        'src/**/designSystem/**',
        'src/**/__figma__/**',
        './vitest.setup.ts',
        'src/**/*.d.ts',
        'src/**/index.ts',
        'src/**/index.tsx',
        'src/**/*.styled.ts',
        'src/**/*.styles.ts',
        'src/**/*.css',
        'src/**/*.svg',
        'src/**/constants/**',
        '.prettierrc.js',
        'stylelint.config.js',
        'vite.config.ts',
        'vitest.config.ts',
        'app/__reports__/test-coverage/lcov-report',
        'prettify.js',
        'public/**',
      ],
      provider: 'v8',
      reporter: ['text', 'json', 'lcov', 'html', 'json-summary'],
      reportsDirectory: '__reports__/test-coverage',
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        perFile: false,
        statements: 80,
      },
    },
    css: false,
    environment: 'jsdom',
    globals: true,
    include: ['./src/**/*.test.ts', './src/**/*.test.tsx'],
    mockReset: true,
    outputFile: {
      html: '__reports__/report.html',
      json: '__reports__/test-results.json',
    },
    reporters: ['default', 'html', 'json'],
    restoreMocks: true,
    setupFiles: './vitest.setup.ts',
    silent: false,
  },
});
