export const ListOptionsVariantType = {
  CODE_VIEWER_SUBTHEME: 'CODE_VIEWER_SUBTHEME',
  DEFAULT: 'DEFAULT',
  DROPDOWN_SELECTED_SECTION: 'DROPDOWN_SELECTED_SECTION',
  INPUT_DROPDOWN_DEFAULT: 'INPUT_DROPDOWN_DEFAULT',
  INPUT_DROPDOWN_SECTION: 'INPUT_DROPDOWN_SECTION',
  INPUT_SEARCH: 'INPUT_SEARCH',
  SIDE_MENU_SECTION: 'SIDE_MENU_SECTION',
} as const;
