export enum CheckboxWithLabelState {
  DEFAULT_UNSELECTED = 'DEFAULT_UNSELECTED',
  DEFAULT_SELECTED = 'DEFAULT_SELECTED',
  DISABLED_UNSELECTED = 'DISABLED_UNSELECTED',
  DISABLED_SELECTED = 'DISABLED_SELECTED',
  ERROR = 'ERROR',
}
