export enum RadioButtonStateType {
  DEFAULT = 'DEFAULT',
  DISABLED = 'DISABLED',
  DISABLED_SELECTED = 'DISABLED_SELECTED',
  SELECTED = 'SELECTED',
  ERROR = 'ERROR',
  ERROR_SELECTED = 'ERROR_SELECTED',
}
