import { STATES } from '@/types/states';

export enum LinkStateType {
  DEFAULT = STATES.DEFAULT,
  DISABLED = STATES.DISABLED,
  HOVER = STATES.HOVER,
  PRESSED = STATES.PRESSED,
  VISITED = STATES.VISITED,
}
