export type ComponentsTypesAvailableComponents = 'ACCORDION' | 'AVATAR' | 'BADGE' | 'BREADCRUMBS' | 'BUTTON' | 'CALENDAR' | 'CARD_IMAGE' | 'CAROUSEL' | 'CHECKBOX' | 'CHECKBOX_BASE' | 'CHIP' | 'CONTAINER' | 'DATA_TABLE' | 'DOT' | 'DROPDOWN_SELECTED' | 'ERROR_MESSAGE' | 'ICON' | 'INPUT' | 'INPUT_BASE' | 'INPUT_DECORATION' | 'INPUT_SIGNATURE' | 'ITEM_ROVE' | 'LINK' | 'LINK_AS_BUTTON' | 'LIST_OPTIONS' | 'MESSAGE' | 'MODAL' | 'NAVBAR' | 'OPTION' | 'OVERLAY' | 'PAGE_CONTROL' | 'PAGINATION' | 'POPOVER' | 'PROGRESS_BAR' | 'RADIO_BUTTON' | 'SELECTOR_BOX_FILE' | 'SKELETON' | 'SLIDER' | 'SNACKBAR' | 'STEPPER_NUMBER' | 'TABLE' | 'TABLE_BODY' | 'TABLE_CAPTION' | 'TABLE_CELL' | 'TABLE_DIVIDER' | 'TABLE_FOOT' | 'TABLE_HEAD' | 'TABLE_ROW' | 'TABS' | 'TAG' | 'TEXT' | 'TEXT_AREA' | 'TEXT_COUNT' | 'TOGGLE' | 'TOOLTIP' | 'VIRTUAL_KEYBOARD'

type NonVariablesKeys<T> = {
  [K in keyof T]: K extends `$${string}` ? never : K;
}[keyof T];
export type ComponentSelected<T> = Pick<T, NonVariablesKeys<T>>;
    
export type ComponentsTypesComponents = {
  ACCORDION: {
    accordion: string,
    content: string,
    header: string,
    headerbutton: string,
    innercontent: string,
    $_neutral: {
      accordion: string,
    },
    $_standard: {
      accordion: string,
    },
  },
  AVATAR: {
    avatar: string,
    dot: string,
    icon: string,
    $_large: {
      avatar: string,
      icon: string,
    },
    $_medium: {
      avatar: string,
      icon: string,
    },
    $_small: {
      avatar: string,
      icon: string,
    },
    $_extra_large: {
      avatar: string,
      icon: string,
    },
  },
  BADGE: {
    badge: string,
    button: string,
    dot: string,
    dotcontainer: string,
    icon: string,
    label: string,
    labelcontainer: string,
    labelicon: string,
    $_default: {
      badge: string,
      icon: string,
    },
    $_alternative: {
      badge: string,
      icon: string,
      label: string,
      labelicon: string,
    },
    $_primary: {
      badge: string,
      icon: string,
      label: string,
      labelicon: string,
    },
  },
  BREADCRUMBS: {
    breadcrumbs: string,
    crumb: string,
    icondivider: string,
    icondividercontainer: string,
    lastonecrumb: string,
    link: string,
    linkcontainer: string,
    $_alternative: {
      breadcrumbs: string,
      icondivider: string,
      lastonecrumb: string,
      link: string,
    },
    $_default: {
      breadcrumbs: string,
      lastonecrumb: string,
      link: string,
    },
  },
  BUTTON: {
    button: string,
    icon: string,
    loader: string,
    $_large: {
      button: string,
      icon: string,
    },
    $_small: {
      button: string,
      icon: string,
    },
    $_action_primary: {
      button: string,
    },
    $_action_secondary: {
      button: string,
    },
    $_action_secondary_alt: {
      button: string,
    },
    $_primary: {
      button: string,
    },
    $_secondary: {
      button: string,
    },
    $_secondary_alt: {
      button: string,
    },
    dynamic_values: (styles: { '$alignText': string; }) => { string: string; object: object } ,
  },
  CALENDAR: {
    calendar: string,
    backtext: string,
    container: string,
    dayslist: string,
    headercontainer: string,
    headerrow: string,
    headerth: string,
    leftarrow: string,
    listelementempty: string,
    listelementrove: string,
    monthelement: string,
    monthlistitem: string,
    monthslist: string,
    rightarrow: string,
    selectorcontainer: string,
    selectoriconandbacktextcontainer: string,
    selectoroptionscontainer: string,
    table: string,
    tablerow: string,
    tbody: string,
    weekdaycontainer: string,
    year: string,
    yearelement: string,
    yearlistitem: string,
    yearslist: string,
    button_size: {
      icon: string,
      button: string,
      loader: string,
    },
    button_variant: {
      button: string,
      icon: string,
      loader: string,
    },
  },
  CARD_IMAGE: {
    card_image: string,
    content: string,
    description: string,
    descriptioncontainer: string,
    imagecontainer: string,
    linkcontainer: string,
    textcontainer: string,
    title: string,
    titlecontainer: string,
    $_alternative: {
      card_image: string,
    },
    $_default: {
      card_image: string,
      description: string,
    },
  },
  CAROUSEL: {
    carousel: string,
    content: string,
    viewer: string,
    $_default: {
      carousel: string,
    },
  },
  CHECKBOX: {
    checkbox: string,
    checkboxwithlabelcontainer: string,
    errormessagecontainer: string,
    label: string,
    error_message: {
      icon: string,
      typography: string,
      error_message: string,
    },
  },
  CHECKBOX_BASE: {
    checkbox_base: string,
    icon: string,
    iconcontainer: string,
    input: string,
    $_default: {
      checkbox_base: string,
    },
  },
  CHIP: {
    chip: string,
    closeicon: string,
    errorcontainer: string,
    erroricon: string,
    errormessage: string,
    label: string,
    lefticon: string,
    rangeicon: string,
    rangeitemseparator: string,
    rangeitemtext: string,
    rangeitemwrapper: string,
    $_default: {
      chip: string,
      closeicon: string,
      errorcontainer: string,
      erroricon: string,
      errormessage: string,
      label: string,
      lefticon: string,
      rangeitemseparator: string,
      rangeitemtext: string,
    },
  },
  CONTAINER: {
    container: string,
    content: string,
    header: string,
    title: string,
    $_alternative: {
      container: string,
    },
    $_default: {
      container: string,
    },
    $_secondary: {
      container: string,
    },
  },
  DATA_TABLE: {
    data_table: string,
    headboxshadow: string,
    leftboxshadow: string,
    leftboxshadowcontainer: string,
    rightboxshadow: string,
    rightboxshadowcontainer: string,
    scrollablecontainer: string,
    $_default: {
      data_table: string,
    },
    row_group_table: {
      container: string,
      headboxshadow: string,
      leftboxshadow: string,
      leftboxshadowcontainer: string,
      rightboxshadow: string,
      rightboxshadowcontainer: string,
      scrollablecontainer: string,
      table: string,
    },
    row_group_table_body: {
      table_body: string,
    },
    row_group_table_body_cell: {
      table_cell: string,
    },
    row_group_table_body_row: {
      table_row: string,
    },
    row_group_table_caption: {
      table_caption: string,
    },
    row_group_table_head: {
      table_head: string,
    },
    row_group_table_head_cell: {
      table_cell: string,
    },
    row_group_table_head_row: {
      table_row: string,
    },
    table: {
      container: string,
      headboxshadow: string,
      leftboxshadow: string,
      leftboxshadowcontainer: string,
      rightboxshadow: string,
      rightboxshadowcontainer: string,
      scrollablecontainer: string,
      table: string,
    },
    table_body: {
      table_body: string,
    },
    table_body_cell: {
      table_cell: string,
    },
    table_body_row: {
      table_row: string,
    },
    table_caption: {
      table_caption: string,
    },
    table_head: {
      table_head: string,
    },
    table_head_cell: {
      table_cell: string,
    },
    table_head_row: {
      table_row: string,
    },
  },
  DOT: {
    dot: string,
    $_big: {
      dot: string,
    },
    $_medium: {
      dot: string,
    },
    $_small: {
      dot: string,
    },
    $_alternative: {
      dot: string,
    },
    $_with_border: {
      dot: string,
    },
    $_without_border: {
      dot: string,
    },
  },
  DROPDOWN_SELECTED: {
    dropdown_selected: string,
    buttonorlinkcontainer: string,
    iconclosed: string,
    iconopened: string,
    labelclosed: string,
    labelopened: string,
    listoptionscontainer: string,
    $_default: {
      dropdown_selected: string,
      buttonorlinkcontainer: string,
      iconclosed: string,
      iconopened: string,
      labelclosed: string,
      labelopened: string,
      listoptionscontainer: string,
    },
    $_side_menu: {
      dropdown_selected: string,
      buttonorlinkcontainer: string,
      iconclosed: string,
      iconopened: string,
      labelclosed: string,
      labelopened: string,
      listoptionscontainer: string,
    },
    $_topbar: {
      dropdown_selected: string,
      buttonorlinkcontainer: string,
      iconclosed: string,
      iconopened: string,
      labelclosed: string,
      labelopened: string,
      listoptionscontainer: string,
    },
    $_topbar_tab: {
      dropdown_selected: string,
      buttonorlinkcontainer: string,
      iconclosed: string,
      iconopened: string,
      labelclosed: string,
      labelopened: string,
      listoptionscontainer: string,
    },
  },
  ERROR_MESSAGE: {
    error_message: string,
    icon: string,
    typography: string,
    $_default: {
      error_message: string,
    },
  },
  ICON: {
    button: string,
    complex: string,
    svg: string,
    dynamic_values: (styles: { '$color': string; '$moveAround': string; '$transitionDuration': string; '$height': string; '$width': string; }) => { string: string; object: object } ,
  },
  INPUT: {
    input: string,
    inputandlabelcontainer: string,
    $_filled: {
      input: string,
    },
    $_outlined: {
      input: string,
    },
    $_standard: {
      input: string,
    },
    input_base: {
      input_base: string,
    },
    left_decoration: {
      decoration: string,
      input_decoration: string,
    },
    right_decoration: {
      decoration: string,
      input_decoration: string,
    },
  },
  INPUT_BASE: {
    input_base: string,
    $_filled: {
      input_base: string,
    },
    $_outlined: {
      input_base: string,
    },
    $_standard: {
      input_base: string,
    },
  },
  INPUT_DECORATION: {
    input_decoration: string,
    decoration: string,
    $_standard: {
      input_decoration: string,
    },
  },
  INPUT_SIGNATURE: {
    input_signature: string,
    canvas: string,
    placeholdercontainer: string,
    placeholdertext: string,
    $_default: {
      input_signature: string,
    },
  },
  ITEM_ROVE: {
    item_rove: string,
  },
  LINK: {
    link: string,
    childrencontainer: string,
    icon: string,
    labelandiconcontainer: string,
    $_inline_primary: {
      link: string,
      icon: string,
    },
    $_inline_secondary: {
      link: string,
      icon: string,
    },
    $_inline_secondary_alt: {
      link: string,
      icon: string,
    },
    $_navigation_primary: {
      link: string,
      icon: string,
    },
    $_navigation_secondary: {
      link: string,
      icon: string,
    },
    $_navigation_secondary_alt: {
      link: string,
      icon: string,
    },
  },
  LINK_AS_BUTTON: {
    link_as_button: string,
  },
  LIST_OPTIONS: {
    list_options: string,
    optionscontainer: string,
    title: string,
    titlecontainer: string,
    $_code_viewer_subtheme: {
      list_options: string,
    },
    $_default: {
      list_options: string,
      title: string,
      titlecontainer: string,
    },
    $_dropdown_selected_section: {
      list_options: string,
      optionscontainer: string,
    },
    $_input_dropdown_default: {
      list_options: string,
    },
    $_input_dropdown_section: {
      list_options: string,
    },
    $_input_search: {
      list_options: string,
    },
    $_side_menu_section: {
      list_options: string,
      optionscontainer: string,
      title: string,
      titlecontainer: string,
    },
  },
  MESSAGE: {
    message: string,
    actionbuttoncontainer: string,
    buttonsectioncontainer: string,
    closeicon: string,
    container: string,
    contentcontainer: string,
    contentcontainerlargemessage: string,
    description: string,
    extraactionbuttoncontainer: string,
    headercontainer: string,
    headercontainerlargemessage: string,
    infoicon: string,
    linkcontainer: string,
    linkscontainer: string,
    title: string,
    titlecontainer: string,
    $_error: {
      message: string,
      container: string,
      infoicon: string,
    },
    $_informative: {
      message: string,
      container: string,
      infoicon: string,
    },
    $_success: {
      message: string,
      container: string,
      infoicon: string,
    },
    $_warning: {
      message: string,
      container: string,
      infoicon: string,
    },
    action_button: {
      button: string,
      icon: string,
      loader: string,
    },
  },
  MODAL: {
    modal: string,
    closebuttoncontainer: string,
    closebuttonicon: string,
    content: string,
    dragicon: string,
    dragiconcontainer: string,
    footer: string,
    headercontainer: string,
    headercontentcontainer: string,
    title: string,
    titlecontainer: string,
    titlehiddencontainer: string,
    $_default: {
      modal: string,
    },
  },
  NAVBAR: {
    navbar: string,
    itemcontainer: string,
    $_default: {
      navbar: string,
    },
  },
  OPTION: {
    option: string,
    checkedicon: string,
    firstrowcontainer: string,
    icon: string,
    label: string,
    labelhighlighted: string,
    labeliconcontainer: string,
    sublabel: string,
    sublabelcontainer: string,
    $_code_viewer_subtheme: {
      option: string,
      label: string,
    },
    $_input_dropdown: {
      option: string,
      icon: string,
      label: string,
      labeliconcontainer: string,
    },
    $_input_option: {
      option: string,
      icon: string,
      label: string,
      labelhighlighted: string,
      labeliconcontainer: string,
      sublabel: string,
    },
    $_input_option_hightlighted: {
      option: string,
      icon: string,
      label: string,
      labelhighlighted: string,
      labeliconcontainer: string,
      sublabel: string,
    },
    $_inverted: {
      option: string,
      label: string,
    },
    $_side_menu_level_1: {
      option: string,
      icon: string,
      label: string,
      labeliconcontainer: string,
    },
    $_side_menu_level_2: {
      option: string,
      label: string,
    },
    $_topbar: {
      option: string,
      label: string,
      labelhighlighted: string,
    },
    $_topbar_tab: {
      option: string,
      label: string,
    },
  },
  OVERLAY: {
    overlay: string,
    $_default: {
      overlay: string,
    },
    $_secondary: {
      overlay: string,
    },
  },
  PAGE_CONTROL: {
    page_control: string,
    dotscontainer: string,
    icon: string,
    leftarrowcontrolcontainer: string,
    leftbuttoncontrol: string,
    pagedot: string,
    rightarrowcontrolcontainer: string,
    rightbuttoncontrol: string,
    $_default: {
      page_control: string,
      icon: string,
    },
    $_bullets: {
      page_control: string,
      dotscontainer: string,
      pagedot: string,
    },
  },
  PAGINATION: {
    pagination: string,
    page: string,
    pagecontainer: string,
    pagescontainer: string,
    paginationleftarrowicon: string,
    paginationrightarrowicon: string,
    $_default: {
      pagination: string,
      page: string,
      paginationleftarrowicon: string,
      paginationrightarrowicon: string,
    },
  },
  POPOVER: {
    popover: string,
    arrow: string,
  },
  PROGRESS_BAR: {
    progress_bar: string,
    bar: string,
    barcontainer: string,
    progressbar: string,
    $_medium: {
      progress_bar: string,
      bar: string,
      progressbar: string,
    },
    $_small: {
      progress_bar: string,
      bar: string,
      progressbar: string,
    },
    $_default: {
      progress_bar: string,
    },
    $_interactive: {
      progress_bar: string,
      barcontainer: string,
    },
    slider: {
      activetrack: string,
      inactivetrack: string,
      thumb: string,
      decrement_button_size: {
        icon: string,
        button: string,
        loader: string,
      },
      decrement_button_variant: {
        button: string,
        icon: string,
        loader: string,
      },
      tooltip: {
        arrowcontainer: string,
        arrowposition: string,
        arrowsize: string,
        closebuttoncontainer: string,
        closebuttonicon: string,
        headercontainer: string,
        paragraph: string,
        paragraphcontainer: string,
        title: string,
        tooltipexternalcontainer: string,
        tooltipinternalcontainer: string,
        popover: {
          arrow: string,
          popover: string,
        },
        arrow: string,
        divider: string,
        dragicon: string,
        dragiconcontainer: string,
        tooltipalignstyles: string,
        tooltipasmodal: string,
      },
      buttonstrackscontainer: string,
      helpertext: string,
      helpertextcontainer: string,
      helpertextleftcontainer: string,
      helpertextrightcontainer: string,
      innerthumbtooltip: string,
      label: string,
      labelcontainer: string,
      rightthumbicon: string,
      scalecontainer: string,
      scaleoption: string,
      thumbicon: string,
      tracksthumbscontainer: string,
      tracksthumbsinnercontainer: string,
      slider: string,
    },
  },
  RADIO_BUTTON: {
    radio_button: string,
    errormessage: string,
    errormessagecontainer: string,
    errormessageicon: string,
    errormessageiconcontainer: string,
    infocontainer: string,
    label: string,
    labelcontainer: string,
    radiobuttoncontainer: string,
    rowcontainer: string,
    speciallabel: string,
    sublabel: string,
    $_default: {
      radio_button: string,
      errormessage: string,
      sublabel: string,
    },
    tooltip: {
      arrowcontainer: string,
      arrowposition: string,
      arrowsize: string,
      closebuttoncontainer: string,
      closebuttonicon: string,
      headercontainer: string,
      paragraph: string,
      paragraphcontainer: string,
      title: string,
      tooltipexternalcontainer: string,
      tooltipinternalcontainer: string,
      popover: {
        arrow: string,
        popover: string,
      },
      arrow: string,
      divider: string,
      dragicon: string,
      dragiconcontainer: string,
      tooltipalignstyles: string,
      tooltipasmodal: string,
    },
  },
  SELECTOR_BOX_FILE: {
    selector_box_file: string,
    actiondescriptioncontainer: string,
    actionicon: string,
    actioniconandactiontextcontainer: string,
    animationcontainer: string,
    borderanimationcontainer: string,
    bottomanimationcontainer: string,
    containeractioncontainer: string,
    containerboxactiontext: string,
    containerboxcontainer: string,
    containerboxdescription: string,
    containerboxfilename: string,
    containerboxicon: string,
    containerboxtextscontainer: string,
    description: string,
    descriptioncontainer: string,
    errormessage: string,
    errormessagecontainer: string,
    errormessageicon: string,
    header: string,
    leftanimationcontainer: string,
    rightanimationcontainer: string,
    subtitle: string,
    subtitletooltipcontainer: string,
    title: string,
    titlesubtitlecontainer: string,
    tooltipicon: string,
    tooltipiconcontainer: string,
    topanimationcontainer: string,
    $_default: {
      selector_box_file: string,
    },
    button_size: {
      icon: string,
      button: string,
      loader: string,
    },
    button_variant: {
      button: string,
      icon: string,
      loader: string,
    },
    tooltip: {
      arrowcontainer: string,
      arrowposition: string,
      arrowsize: string,
      closebuttoncontainer: string,
      closebuttonicon: string,
      headercontainer: string,
      paragraph: string,
      paragraphcontainer: string,
      title: string,
      tooltipexternalcontainer: string,
      tooltipinternalcontainer: string,
      popover: {
        arrow: string,
        popover: string,
      },
      arrow: string,
      divider: string,
      dragicon: string,
      dragiconcontainer: string,
      tooltipalignstyles: string,
      tooltipasmodal: string,
    },
  },
  SKELETON: {
    skeleton: string,
    $_circle: {
      skeleton: string,
    },
    $_square: {
      skeleton: string,
    },
    $_alternative: {
      skeleton: string,
    },
    $_default: {
      skeleton: string,
    },
  },
  SLIDER: {
    slider: string,
    activetrack: string,
    buttonstrackscontainer: string,
    helpertext: string,
    helpertextcontainer: string,
    helpertextleftcontainer: string,
    helpertextrightcontainer: string,
    inactivetrack: string,
    innerthumbtooltip: string,
    label: string,
    labelcontainer: string,
    rightthumbicon: string,
    scalecontainer: string,
    scaleoption: string,
    thumb: string,
    thumbicon: string,
    tracksthumbscontainer: string,
    tracksthumbsinnercontainer: string,
    $_primary: {
      slider: string,
      activetrack: string,
      inactivetrack: string,
      thumb: string,
    },
    $_test_no_thumb_exceeds_track: {
      slider: string,
    },
    decrement_button_size: {
      icon: string,
      button: string,
      loader: string,
    },
    decrement_button_variant: {
      button: string,
      icon: string,
      loader: string,
    },
    tooltip: {
      arrowcontainer: string,
      arrowposition: string,
      arrowsize: string,
      closebuttoncontainer: string,
      closebuttonicon: string,
      headercontainer: string,
      paragraph: string,
      paragraphcontainer: string,
      title: string,
      tooltipexternalcontainer: string,
      tooltipinternalcontainer: string,
      popover: {
        arrow: string,
        popover: string,
      },
      arrow: string,
      divider: string,
      dragicon: string,
      dragiconcontainer: string,
      tooltipalignstyles: string,
      tooltipasmodal: string,
    },
  },
  SNACKBAR: {
    $_error: {
      snackbar: string,
      container: string,
    },
    $_container: {
      snackbar: string,
    },
    container: string,
    $_primary: {
      snackbar: string,
      container: string,
    },
    $_success: {
      snackbar: string,
      container: string,
    },
    $_warning: {
      snackbar: string,
      container: string,
    },
  },
  STEPPER_NUMBER: {
    stepper_number: string,
    iconselected: string,
    stepbar: string,
    stepcircle: string,
    stepcirclecontainer: string,
    stepcontainer: string,
    stepindex: string,
    stepname: string,
    stepnamecontainer: string,
    $_horizontal: {
      stepper_number: string,
      stepindex: string,
    },
    $_default: {
      stepper_number: string,
      iconselected: string,
      stepbar: string,
      stepcircle: string,
      stepindex: string,
    },
    $_vertical: {
      stepper_number: string,
      stepcontainer: string,
      stepname: string,
      stepnamecontainer: string,
    },
  },
  TABLE: {
    table: string,
    container: string,
    headboxshadow: string,
    leftboxshadow: string,
    leftboxshadowcontainer: string,
    rightboxshadow: string,
    rightboxshadowcontainer: string,
    scrollablecontainer: string,
    $_default: {
      table: string,
    },
  },
  TABLE_BODY: {
    table_body: string,
    $_default: {
      table_body: string,
    },
  },
  TABLE_CAPTION: {
    table_caption: string,
    $_default: {
      table_caption: string,
    },
  },
  TABLE_CELL: {
    table_cell: string,
    $_body_cell_default: {
      table_cell: string,
    },
    $_header_cell_default: {
      table_cell: string,
    },
    $_header_cell_secondary: {
      table_cell: string,
    },
    dynamic_values: (styles: { '$tdWidth': string; '$tdHeight': string; '$tdMinWidth': string; '$tdMaxWidth': string; '$tdTextAlign': string; '$tdVerticalAlign': string; '$tdAlignItems': string; '$tdJustifyContent': string; '$tdTop': string; '$tdLeft': string; '$tdRight': string; '$tdBottom': string; }) => { string: string; object: object } ,
  },
  TABLE_DIVIDER: {
    table_divider: string,
    $_default: {
      table_divider: string,
    },
  },
  TABLE_FOOT: {
    table_foot: string,
    $_default: {
      table_foot: string,
    },
  },
  TABLE_HEAD: {
    table_head: string,
    $_default: {
      table_head: string,
    },
  },
  TABLE_ROW: {
    table_row: string,
    $_body_row_default: {
      table_row: string,
    },
    $_header_row_default: {
      table_row: string,
    },
    $_header_row_secondary: {
      table_row: string,
    },
  },
  TABS: {
    tabs: string,
    arrowiconcontainer: string,
    container: string,
    contentcontainer: string,
    firsttabbutton: string,
    icon: string,
    label: string,
    lasttabbutton: string,
    onetabcontainer: string,
    tabbutton: string,
    tabbuttonscontainer: string,
    tabcontainer: string,
    $_default: {
      tabs: string,
    },
  },
  TAG: {
    tag: string,
    icon: string,
    label: string,
    $_code: {
      tag: string,
      label: string,
    },
    $_deprecated: {
      tag: string,
    },
    $_dormant: {
      tag: string,
    },
    $_healthy: {
      tag: string,
    },
    $_informative: {
      tag: string,
    },
    $_issue: {
      tag: string,
    },
  },
  TEXT: {
    text: string,
    $_default: {
      text: string,
    },
    $_heading_display_1_expanded: {
      text: string,
    },
    $_heading_display_1_extended: {
      text: string,
    },
    $_heading_h1_expanded: {
      text: string,
    },
    $_heading_h1_extended: {
      text: string,
    },
    $_heading_h2_expanded: {
      text: string,
    },
    $_heading_h2_extended: {
      text: string,
    },
    $_heading_h3_expanded: {
      text: string,
    },
    $_heading_h3_extended: {
      text: string,
    },
    $_heading_h4_expanded: {
      text: string,
    },
    $_heading_h4_extended: {
      text: string,
    },
    $_main_heading_display_1_expanded: {
      text: string,
    },
    $_main_heading_h1_expanded: {
      text: string,
    },
    $_main_heading_h2_expanded: {
      text: string,
    },
    $_main_heading_h3_expanded: {
      text: string,
    },
    $_main_heading_h4_expanded: {
      text: string,
    },
    $_paragraph_caption_expanded: {
      text: string,
    },
    $_paragraph_caption_extended: {
      text: string,
    },
    $_paragraph_large_expanded: {
      text: string,
    },
    $_paragraph_large_extended: {
      text: string,
    },
    $_paragraph_medium_expanded: {
      text: string,
    },
    $_paragraph_medium_extended: {
      text: string,
    },
    $_paragraph_medium_mono: {
      text: string,
    },
    $_paragraph_small_expanded: {
      text: string,
    },
    $_paragraph_small_extended: {
      text: string,
    },
  },
  TEXT_AREA: {
    text_area: string,
    bottomcontainer: string,
    counter: string,
    counterleft: string,
    counterright: string,
    errorcontainer: string,
    erroricon: string,
    errormessage: string,
    helpmessage: string,
    helpmessageerrorcontainer: string,
    label: string,
    labelandadditionalinfocontainer: string,
    labeltextareacontainer: string,
    required: string,
    textarea: string,
    title: string,
    titlecontainer: string,
    $_default: {
      text_area: string,
    },
  },
  TEXT_COUNT: {
    text_count: string,
    letftext: string,
    righttext: string,
    $_default: {
      text_count: string,
      letftext: string,
      righttext: string,
    },
  },
  TOGGLE: {
    icon: string,
    iconwrapper: string,
    thumb: string,
    track: string,
    $_regular: {
      toggle: string,
      track: string,
    },
  },
  TOOLTIP: {
    arrow: string,
    arrowcontainer: string,
    arrowposition: string,
    arrowsize: string,
    closebuttoncontainer: string,
    closebuttonicon: string,
    divider: string,
    dragicon: string,
    dragiconcontainer: string,
    headercontainer: string,
    paragraph: string,
    paragraphcontainer: string,
    title: string,
    tooltipalignstyles: string,
    tooltipasmodal: string,
    tooltipexternalcontainer: string,
    tooltipinternalcontainer: string,
    $_default: {
      tooltip: string,
      arrowcontainer: string,
      arrowposition: string,
      arrowsize: string,
      closebuttoncontainer: string,
      closebuttonicon: string,
      headercontainer: string,
      paragraph: string,
      paragraphcontainer: string,
      title: string,
      tooltipexternalcontainer: string,
      tooltipinternalcontainer: string,
    },
    popover: {
      arrow: string,
      popover: string,
    },
  },
  VIRTUAL_KEYBOARD: {
    virtual_keyboard: string,
    digitbuttons: string,
    digittext: string,
    digitwrapper: string,
    iconcontainer: string,
    removebutton: string,
    $_default: {
      virtual_keyboard: string,
      digitbuttons: string,
      digittext: string,
    },
  },
}