export enum TextVariantType {
  //expanded
  HEADING_DISPLAY_1_EXPANDED = 'HEADING_DISPLAY_1_EXPANDED',
  HEADING_H1_EXPANDED = 'HEADING_H1_EXPANDED',
  HEADING_H2_EXPANDED = 'HEADING_H2_EXPANDED',
  HEADING_H3_EXPANDED = 'HEADING_H3_EXPANDED',
  HEADING_H4_EXPANDED = 'HEADING_H4_EXPANDED',
  PARAGRAPH_LARGE_EXPANDED = 'PARAGRAPH_LARGE_EXPANDED',
  PARAGRAPH_MEDIUM_EXPANDED = 'PARAGRAPH_MEDIUM_EXPANDED',
  PARAGRAPH_SMALL_EXPANDED = 'PARAGRAPH_SMALL_EXPANDED',
  PARAGRAPH_CAPTION_EXPANDED = 'PARAGRAPH_CAPTION_EXPANDED',

  // extended
  HEADING_DISPLAY_1_EXTENDED = 'HEADING_DISPLAY_1_EXTENDED',
  HEADING_H1_EXTENDED = 'HEADING_H1_EXTENDED',
  HEADING_H2_EXTENDED = 'HEADING_H2_EXTENDED',
  HEADING_H3_EXTENDED = 'HEADING_H3_EXTENDED',
  HEADING_H4_EXTENDED = 'HEADING_H4_EXTENDED',
  PARAGRAPH_LARGE_EXTENDED = 'PARAGRAPH_LARGE_EXTENDED',
  PARAGRAPH_MEDIUM_EXTENDED = 'PARAGRAPH_MEDIUM_EXTENDED',
  PARAGRAPH_SMALL_EXTENDED = 'PARAGRAPH_SMALL_EXTENDED',
  PARAGRAPH_CAPTION_EXTENDED = 'PARAGRAPH_CAPTION_EXTENDED',
  DEFAULT = 'DEFAULT',
  PARAGRAPH_MEDIUM_MONO = 'PARAGRAPH_MEDIUM_MONO',

  // main
  MAIN_HEADING_DISPLAY_1_EXPANDED = 'MAIN_HEADING_DISPLAY_1_EXPANDED',
  MAIN_HEADING_H1_EXPANDED = 'MAIN_HEADING_H1_EXPANDED',
  MAIN_HEADING_H2_EXPANDED = 'MAIN_HEADING_H2_EXPANDED',
  MAIN_HEADING_H3_EXPANDED = 'MAIN_HEADING_H3_EXPANDED',
  MAIN_HEADING_H4_EXPANDED = 'MAIN_HEADING_H4_EXPANDED',
}
