const PROPERTY_TO_HANDLE_TRANSITION_END = 'left';
const THRESHOLD_TO_DECIDE_IF_ALLOW_DRAGGING = 20;
const THRESHOLD_TO_DECIDE_IF_SWIPE_ON_DRAG_ENDS = 0;

export default {
  PROPERTY_TO_HANDLE_TRANSITION_END,
  THRESHOLD_TO_DECIDE_IF_ALLOW_DRAGGING,
  THRESHOLD_TO_DECIDE_IF_SWIPE_ON_DRAG_ENDS,
};
