declare module '*.webp';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.svg';
declare module '*.ttf';
declare module '*.eot';
declare module '*.otf';
declare module '*.mdx';
