/**
 * Option state type
 * @export
 * @enum {string}
 */
export enum OptionStateType {
  DEFAULT = 'DEFAULT',
  FILLING = 'FILLING',
  HOVER = 'HOVER',
  SELECTED = 'SELECTED',
  SELECTED_HOVER = 'SELECTED_HOVER',
  MULTIPLE_SELECTED = 'MULTIPLE_SELECTED',
  MULTIPLE_SELECTED_HOVER = 'MULTIPLE_SELECTED_HOVER',
  DISABLED = 'DISABLED',
  FOCUS = 'FOCUS',
}
