export enum TagVariantType {
  SQUARE = 'SQUARE',
  ARROW = 'ARROW',
  RIBBON = 'RIBBON',
}

export enum TagOptionType {
  HEALTHY = 'HEALTHY',
  DORMANT = 'DORMANT',
  ISSUE = 'ISSUE',
  CODE = 'CODE',
  DEPRECATED = 'DEPRECATED',
  INFORMATIVE = 'INFORMATIVE',
  TESTING_BORDER_TRANSPARENCY = 'TESTING_BORDER_TRANSPARENCY',
  TESTING_BORDER_NO_TRANSPARENCY = 'TESTING_BORDER_NO_TRANSPARENCY',
  TESTING_NO_BORDER_TRANSPARENCY = 'TESTING_NO_BORDER_TRANSPARENCY',
  TESTING_NO_BORDER_NO_TRANSPARENCY = 'TESTING_NO_BORDER_NO_TRANSPARENCY',
}

export enum TagStatusType {
  NORMAL = 'NORMAL',
}
