export enum ButtonVariantType {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  SECONDARY_ALT = 'SECONDARY_ALT',
  ACTION_PRIMARY = 'ACTION_PRIMARY',
  ACTION_SECONDARY = 'ACTION_SECONDARY',
  ACTION_SECONDARY_ALT = 'ACTION_SECONDARY_ALT',
}

export enum ButtonSizeType {
  LARGE = 'LARGE',
  MEDIUM = 'MEDIUM',
  SMALL = 'SMALL',
}
