export enum ListOptionsVariantType {
  DEFAULT = 'DEFAULT',
  // Not used in side menu
  SIDE_MENU_SECTION = 'SIDE_MENU_SECTION',
  INPUT_DROPDOWN_SECTION = 'INPUT_DROPDOWN_SECTION',
  INPUT_DROPDOWN_DEFAULT = 'INPUT_DROPDOWN_DEFAULT',
  CODE_VIEWER_SUBTHEME = 'CODE_VIEWER_SUBTHEME',
  INPUT_SEARCH = 'INPUT_SEARCH',
  DROPDOWN_SELECTED_SECTION = 'DROPDOWN_SELECTED_SECTION',
}
