export enum OptionVariantType {
  INPUT_OPTION = 'INPUT_OPTION',
  INPUT_OPTION_HIGHTLIGHTED = 'INPUT_OPTION_HIGHTLIGHTED',
  SIDE_MENU_LEVEL_1 = 'SIDE_MENU_LEVEL_1',
  SIDE_MENU_LEVEL_2 = 'SIDE_MENU_LEVEL_2',
  CODE_VIEWER_SUBTHEME = 'CODE_VIEWER_SUBTHEME',
  INPUT_DROPDOWN = 'INPUT_DROPDOWN',
  INVERTED = 'INVERTED',
  TOPBAR = 'TOPBAR',
  TOPBAR_TAB = 'TOPBAR_TAB',
}
